import {identity,db,bucket,json,failure,ownedVisit,ownedList,HttpError} from '@/lib/server';
import {visitSchema,chinaDate} from '@/lib/diary';
import {z} from 'zod';
export async function GET(req:Request){try{const owner=await identity(req);const [vs,ps,ls,its]=await Promise.all([db().prepare('SELECT payload FROM visits WHERE owner=? ORDER BY arrived DESC').bind(owner).all<{payload:string}>(),db().prepare('SELECT id,visit_id FROM photos WHERE owner=?').bind(owner).all<{id:string;visit_id:string}>(),db().prepare('SELECT id,title,created FROM lists WHERE owner=? ORDER BY created DESC').bind(owner).all(),db().prepare('SELECT list_id,payload FROM items WHERE owner=?').bind(owner).all<{list_id:string;payload:string}>()]);return json({visits:vs.results.map(r=>{const v=JSON.parse(r.payload);return {...v,photoIds:ps.results.filter(p=>p.visit_id===v.id).map(p=>p.id)}}),lists:ls.results.map(l=>({...l,items:its.results.filter(i=>i.list_id===l.id).map(i=>JSON.parse(i.payload))}))})}catch(e){return failure(e)}}
export async function POST(req:Request){try{const owner=await identity(req);if(Number(req.headers.get('content-length'))>100000)throw new HttpError(413,'内容过长');const raw=z.record(z.unknown()).parse(await req.json());const action=raw.action;
if(action==='saveVisit'){const v=visitSchema.parse(raw.visit);const taken=await db().prepare('SELECT owner FROM visits WHERE id=?').bind(v.id).first<{owner:string}>();if(taken&&taken.owner!==owner)throw new HttpError(403,'无法修改此记录');await db().prepare('INSERT INTO visits(id,owner,place_key,arrived,payload) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET place_key=excluded.place_key,arrived=excluded.arrived,payload=excluded.payload WHERE visits.owner=excluded.owner').bind(v.id,owner,v.placeKey,v.arrived,JSON.stringify(v)).run();return json({id:v.id})}
if(action==='deleteVisit'){const id=z.string().uuid().parse(raw.id);await ownedVisit(owner,id);const ps=await db().prepare('SELECT object_key FROM photos WHERE visit_id=? AND owner=?').bind(id,owner).all<{object_key:string}>();if(ps.results.length)await bucket().delete(ps.results.map(p=>p.object_key));await db().batch([db().prepare('DELETE FROM photos WHERE visit_id=? AND owner=?').bind(id,owner),db().prepare('DELETE FROM visits WHERE id=? AND owner=?').bind(id,owner)]);return json({ok:true})}
if(action==='createList'){const title=z.string().trim().min(1).max(60).parse(raw.title);const id=z.string().uuid().parse(raw.id);await db().prepare('INSERT INTO lists(id,owner,title,created) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,owner,title,new Date().toISOString()).run();return json({id})}
if(action==='addToList'){const listId=z.string().uuid().parse(raw.listId);await ownedList(owner,listId);const visitId=z.string().uuid().parse(raw.visitId);const v=await ownedVisit(owner,visitId);const itemId=z.string().uuid().parse(raw.id);const existing=await db().prepare('SELECT id FROM items WHERE id=? AND owner=?').bind(itemId,owner).first();if(existing)return json({id:itemId});const photos=await db().prepare('SELECT object_key FROM photos WHERE visit_id=? AND owner=?').bind(visitId,owner).all<{object_key:string}>();const photoIds:string[]=[];const copied:string[]=[];
try{for(let i=0;i<photos.results.length;i++){const object=await bucket().get(photos.results[i].object_key);if(!object)throw new HttpError(503,'照片暂时不可用，请重试');const key=`shared/${owner}/${itemId}/${i}.jpg`;await bucket().put(key,object.body,{httpMetadata:{contentType:'image/jpeg'}});copied.push(key);photoIds.push(`${itemId}_${i}`)}const snapshot={id:itemId,name:v.name,address:v.address,category:v.category,date:chinaDate(v.arrived),rating:v.rating,note:v.note,photoIds};await db().prepare('INSERT INTO items(id,owner,list_id,payload) VALUES(?,?,?,?)').bind(itemId,owner,listId,JSON.stringify(snapshot)).run()}catch(e){if(copied.length)await bucket().delete(copied);throw e}return json({id:itemId})}
if(action==='removeItem'||action==='deleteList'){const id=z.string().uuid().parse(raw.id);if(action==='deleteList')await ownedList(owner,id);const rows=await db().prepare(action==='deleteList'?'SELECT id,payload FROM items WHERE list_id=? AND owner=?':'SELECT id,payload FROM items WHERE id=? AND owner=?').bind(id,owner).all<{id:string;payload:string}>();const keys=rows.results.flatMap(r=>JSON.parse(r.payload).photoIds.map((_:string,i:number)=>`shared/${owner}/${r.id}/${i}.jpg`));if(keys.length)await bucket().delete(keys);if(action==='deleteList')await db().batch([db().prepare('DELETE FROM items WHERE list_id=? AND owner=?').bind(id,owner),db().prepare('DELETE FROM lists WHERE id=? AND owner=?').bind(id,owner)]);else await db().prepare('DELETE FROM items WHERE id=? AND owner=?').bind(id,owner).run();return json({ok:true})}
if(action==='deleteAll'){if(raw.confirm!=='删除我的全部记录')throw new HttpError(400,'请输入确认文字');const keys=await db().prepare('SELECT object_key FROM photos WHERE owner=?').bind(owner).all<{object_key:string}>();const items=await db().prepare('SELECT id,payload FROM items WHERE owner=?').bind(owner).all<{id:string;payload:string}>();const all=[...keys.results.map(x=>x.object_key),...items.results.flatMap(r=>JSON.parse(r.payload).photoIds.map((_:string,i:number)=>`shared/${owner}/${r.id}/${i}.jpg`))];for(let i=0;i<all.length;i+=100)await bucket().delete(all.slice(i,i+100));await db().batch(['photos','visits','items','lists'].map(table=>db().prepare(`DELETE FROM ${table} WHERE owner=?`).bind(owner)));return json({ok:true})}
throw new HttpError(400,'不支持的操作')
}catch(e){return failure(e)}}
