'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {MapPin,Plus,BookOpen,Heart,Settings,Map as MapIcon,LockKeyhole,Star,Search,Navigation,Camera,Trash2,Download,Share2,RefreshCw,Check,WifiOff,LoaderCircle,X,ExternalLink,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Empty,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {average,chinaDate,escapeHtml,type Visit,type DiaryList,type Snapshot,visitSchema} from '@/lib/diary';
import {api,readDiary,currentLocation,localInput,compressPhoto,download,dataUrl} from '@/lib/client';
import MapView,{Nearby} from './map-view';
const fmt=(s:string)=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s));
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
function Rating({value}:{value:number|null}){return <span className={`rating ${value===null?'unrated':''}`}><Star size={15} fill={value!==null?'currentColor':'none'}/>{value===null?'未评分':`${value.toFixed(1)} 分`}</span>}
const blank=():Visit=>({id:crypto.randomUUID(),placeKey:crypto.randomUUID(),name:'',address:'',category:'餐厅',arrived:new Date().toISOString(),departed:null,rating:null,note:'',location:null,photoIds:[]});
type PendingPhoto={id:string;file:File;preview:string};
export default function Diary({email}:{email:string|null}){
 const [visits,setVisits]=useState<Visit[]>([]),[lists,setLists]=useState<DiaryList[]>([]),[tab,setTab]=useState('journal'),[loading,setLoading]=useState(!!email),[error,setError]=useState(''),[online,setOnline]=useState(true);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[date,setDate]=useState('');
 const [draft,setDraft]=useState<Visit|null>(null),[pending,setPending]=useState<PendingPhoto[]>([]),[saving,setSaving]=useState(false),[locating,setLocating]=useState(false),[formError,setFormError]=useState('');
 const [selected,setSelected]=useState<Visit|null>(null),[confirm,setConfirm]=useState<{title:string;description:string;action:()=>Promise<void>}|null>(null),[busy,setBusy]=useState(false);
 const [listDialog,setListDialog]=useState(false),[listTitle,setListTitle]=useState(''),[activeListId,setActiveListId]=useState<string|null>(null),[shareVisit,setShareVisit]=useState<Visit|null>(null),[targetList,setTargetList]=useState('');
 const [deleteText,setDeleteText]=useState(''),[exporting,setExporting]=useState(false),[showSearch,setShowSearch]=useState(false);
 const dataRef=useRef({visits,lists});dataRef.current={visits,lists};
 const reload=useCallback(async()=>{if(!email)return;setLoading(true);try{const d=await readDiary();setVisits(d.visits);setLists(d.lists);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[email]);
 useEffect(()=>{reload();const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[reload]);
 useEffect(()=>{const doc=document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}};if(!doc.modelContext?.registerTool)return;const lifecycle=new AbortController();const register=(t:unknown)=>Promise.resolve(doc.modelContext!.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});register({name:'read_visit_summary',description:'读取当前已加载的私人到访记录和统计。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('不接受参数');return {visits:dataRef.current.visits.map(({id,name,arrived,rating})=>({id,name,arrived,rating})),count:dataRef.current.visits.length}}});register({name:'start_visit_entry',description:'打开新增到访表单并填写店名，不会保存或请求定位。',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:100}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='name')||(input.name!==undefined&&(typeof input.name!=='string'||input.name.length>100)))throw new Error('店名须为 100 字以内的文本');if(!email)throw new Error('请先登录');setDraft({...blank(),name:input.name||''});setFormError('');return {status:'form_opened',saved:false}}});return()=>lifecycle.abort()},[email]);
 const filtered=useMemo(()=>visits.filter(v=>(!query||`${v.name} ${v.address} ${v.note}`.toLowerCase().includes(query.toLowerCase()))&&(!date||chinaDate(v.arrived)===date)&&(filter==='all'||filter==='unrated'&&v.rating===null||filter==='loved'&&v.rating!==null&&v.rating>=4||filter===v.category)),[visits,query,date,filter]);
 const avg=average(visits),shops=new Set(visits.map(v=>v.placeKey)).size;
 const activeList=lists.find(l=>l.id===activeListId)??null;
 function start(v?:Visit){if(!email){location.href='/signin-with-chatgpt?return_to=%2F';return}setSelected(null);setFormError('');setPending([]);setDraft(v?{...v}:blank());setShowSearch(false)}
 function clearDraft(){pending.forEach(p=>URL.revokeObjectURL(p.preview));setPending([]);setDraft(null);setFormError('')}
 async function locate(){setLocating(true);setFormError('');try{const loc=await currentLocation();setDraft(d=>d?{...d,location:loc}:null);if(loc.accuracy&&loc.accuracy>100)toast('定位精度较低，请核对店铺地址')}catch(e){setFormError((e as Error).message)}finally{setLocating(false)}}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||saving)return;setSaving(true);setFormError('');try{visitSchema.parse(draft);await api('saveVisit',{visit:draft});const uploaded:string[]=[];for(const p of pending){try{const blob=await compressPhoto(p.file);const r=await fetch(`/api/photos/${p.id}?visit=${draft.id}`,{method:'PUT',headers:{'Content-Type':'image/jpeg'},body:blob});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);uploaded.push(p.id)}catch(e){setDraft(d=>d?{...d,photoIds:[...new Set([...d.photoIds,...uploaded])]}:null);setPending(ps=>ps.filter(p=>{if(uploaded.includes(p.id)){URL.revokeObjectURL(p.preview);return false}return true}));throw new Error(`记录已保存，部分照片未上传：${(e as Error).message}。可再次点击保存重试。`)}}clearDraft();await reload();toast.success('已保存这次到访')}catch(e){setFormError((e as any).issues?'请检查店名、评分和到访时间':(e as Error).message)}finally{setSaving(false)}}
 async function removePhoto(id:string){if(!draft)return;try{const r=await fetch(`/api/photos/${id}`,{method:'DELETE'});if(!r.ok)throw new Error('照片删除失败');setDraft(d=>d?{...d,photoIds:d.photoIds.filter(x=>x!==id)}:null);await reload()}catch(e){toast.error((e as Error).message)}}
 async function createList(){if(!listTitle.trim())return;setBusy(true);try{const id=crypto.randomUUID();await api('createList',{id,title:listTitle.trim()});await reload();setListDialog(false);setListTitle('');setActiveListId(id);setTargetList(id);toast.success('清单已创建')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function addSnapshot(){if(!shareVisit||!targetList)return;setBusy(true);try{await api('addToList',{listId:targetList,visitId:shareVisit.id,id:crypto.randomUUID()});await reload();setShareVisit(null);toast.success('独立副本已加入清单')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function exportList(list:DiaryList){setExporting(true);try{let html='';for(const item of list.items){const photos=await Promise.all(item.photoIds.map(dataUrl));html+=`<article><p class="date">${escapeHtml(item.date)} · ${escapeHtml(item.category)}</p><h2>${escapeHtml(item.name)}</h2><p>${escapeHtml(item.address)}</p><strong>${item.rating===null?'未评分':item.rating+' / 5 分'}</strong><p class="note">${escapeHtml(item.note)}</p><div class="photos">${photos.map(src=>`<img src="${src}" alt="探店照片">`).join('')}</div></article>`}const text=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(list.title)} · 行迹</title><style>body{font:16px/1.7 -apple-system,BlinkMacSystemFont,sans-serif;margin:0 auto;padding:30px 22px;max-width:740px;background:#f6f8f7;color:#193b2f}h1{font-size:30px}h2{margin:4px 0}.date,footer{color:#63756b;font-size:14px}article{background:white;padding:22px;margin:20px 0;border:1px solid #dce5e0;border-radius:16px}.note{white-space:pre-wrap}.photos{display:flex;flex-wrap:wrap;gap:10px}.photos img{width:calc(50% - 5px);height:220px;object-fit:cover;border-radius:10px}</style><h1>${escapeHtml(list.title)}</h1><p>行迹 · 精选 ${list.items.length} 次到访</p>${html}<footer>这是一份独立清单副本，仅包含主动选入的内容。导出日期：${chinaDate(new Date().toISOString())}</footer></html>`;const file=new File([text],`${list.title.replace(/[\\/:*?"<>|]/g,'_')}.html`,{type:'text/html'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:list.title})}catch(e){if((e as Error).name!=='AbortError')download(file,file.name)}}else download(file,file.name);toast.success('清单已导出，可发送给好友')}catch(e){toast.error((e as Error).message)}finally{setExporting(false)}}
 async function exportAll(){setExporting(true);try{const photoIds=[...new Set([...visits.flatMap(v=>v.photoIds),...lists.flatMap(l=>l.items.flatMap(i=>i.photoIds))])];const photos:Record<string,string>={};let size=0;for(const id of photoIds){photos[id]=await dataUrl(id);size+=photos[id].length;if(size>120000000)throw new Error('照片较多，请分清单导出照片；完整导出暂限 120 MB')}download(new Blob([JSON.stringify({format:'xingji-export',version:1,exportedAt:new Date().toISOString(),visits,lists,photos},null,2)],{type:'application/json'}),`行迹-${chinaDate(new Date().toISOString())}.json`);toast.success('记录与照片已导出')}catch(e){toast.error((e as Error).message)}finally{setExporting(false)}}
 const detail=selected?visits.find(v=>v.id===selected.id)??selected:null;
 return <main className="shell"><Toaster position="top-center"/><header className="topbar"><a className="brand" href="/"><img src="/icon.png" alt=""/><span>行迹<small>我的探店本</small></span></a><span className="privacy"><LockKeyhole size={15}/> 仅自己可见</span></header>
 {!online&&<p className="notice"><WifiOff size={18}/>网络已断开，暂时无法保存。请保留当前页面，联网后重试。</p>}
 {!email&&<div className="signin-banner"><div><b>登录后，开始你的探店记录</b><p>用同一个 ChatGPT 账号，在手机和 Mac 上查看。</p></div><a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="primary">登录</a></div>}
 <Tabs value={tab} onValueChange={setTab}><div className="page-heading"><div><span className="eyebrow">每一次到店，都值得留下</span><h1>{tab==='journal'?'我的足迹':tab==='map'?'探店地图':tab==='lists'?'我的清单':'使用设置'}</h1></div><button className="primary" onClick={()=>start()}><Plus size={20}/>记一笔</button></div>
 {(tab==='journal'||tab==='map')&&<div className="stats"><div><b>{visits.length}</b><span>到访记录</span></div><div><b>{shops}</b><span>去过的店</span></div><div><b>{avg===null?'—':avg.toFixed(1)}</b><span>已评分均值</span></div></div>}
 <TabsList className="navigation"><TabsTrigger value="journal"><BookOpen/>回顾</TabsTrigger><TabsTrigger value="map"><MapIcon/>地图</TabsTrigger><TabsTrigger value="lists"><Heart/>清单</TabsTrigger><TabsTrigger value="settings"><Settings/>设置</TabsTrigger></TabsList>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={reload}><RefreshCw size={15}/>重试</button></div>}
 {(tab==='journal'||tab==='map')&&<div className="filters"><div className="search-input"><Search size={18}/><input aria-label="搜索我的记录" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索店名、地址或感受"/></div><Choice label="筛选记录" value={filter} onChange={setFilter} options={[["all","全部记录"],["loved","4 分及以上"],["unrated","待评分"],["餐厅","餐厅"],["咖啡","咖啡"],["购物","购物"],["其他","其他"]]}/><input type="date" aria-label="按到访日期筛选（北京时间）" value={date} onChange={e=>setDate(e.target.value)}/>{date&&<button className="icon-button" aria-label="清除日期" onClick={()=>setDate('')}><X size={16}/></button>}</div>}
 <TabsContent value="journal"><section className="section-title"><h2>{filter==='all'&&!query&&!date?'最近到访':'筛选结果'}</h2><span>{visits.length?`${filtered.length} 次记录`:'从今天开始记录'}</span></section>
 {loading?<div className="record-grid">{[1,2,3].map(i=><Skeleton key={i} className="h-52 rounded-2xl"/>)}</div>:filtered.length?<div className="record-grid">{filtered.map(v=><button key={v.id} className="visit-card" onClick={()=>setSelected(v)}><div className="card-top"><span className="category">{v.category}</span><Rating value={v.rating}/></div><h3>{v.name}</h3><p className="address"><MapPin size={14}/>{v.address||'未填写地址'}</p>{v.photoIds.length>0&&<img className="visit-cover" src={`/api/photos/${v.photoIds[0]}`} alt={`${v.name}的探店照片`} loading="lazy"/>}{v.note&&<p className="card-note">{v.note}</p>}<div className="card-bottom"><span>{fmt(v.arrived)}</span><span>{visits.filter(x=>x.placeKey===v.placeKey).length>1?'再次到访':'手动记录'}<ChevronRight size={14}/></span></div></button>)}</div>:<Empty className="empty-card"><img src="/coffee.jpg" className="empty-photo" alt=""/><div className="empty-copy"><EmptyTitle>{visits.length?'没有找到符合条件的记录':'记下你去过的第一家店'}</EmptyTitle><EmptyDescription>{visits.length?'换一个关键词或筛选条件试试。':'选一家店，留下到访时间。评分、感受和照片，都可以慢慢补上。'}</EmptyDescription><button className="primary" onClick={()=>visits.length?(setFilter('all'),setQuery(''),setDate('')):start()}>{visits.length?'清除筛选':<><Plus size={18}/>添加到访</>}</button></div></Empty>}
 </TabsContent>
 <TabsContent value="map">{email?<MapView visits={filtered} onSelect={setSelected}/>:<Empty><EmptyTitle>登录后查看你的探店地图</EmptyTitle></Empty>}</TabsContent>
 <TabsContent value="lists"><section className="section-title"><h2>留给自己，也分享给朋友</h2><button className="text-button" onClick={()=>{if(!email){start();return}setListDialog(true)}}><Plus size={17}/>新建清单</button></section><p className="hint">选择到访记录，预览后加入清单。分享文件只包含选中的内容；私人记录修改后，清单不会自动更新。</p>{activeList?<div className="list-detail"><button className="text-button" onClick={()=>setActiveListId(null)}>全部清单</button><div className="section-title"><h2>{activeList.title}</h2><div className="actions"><button className="secondary" disabled={!activeList.items.length||exporting} onClick={()=>exportList(activeList)}><Share2 size={17}/>{exporting?'正在导出':'导出分享'}</button><button className="icon-button danger" aria-label="删除清单" onClick={()=>setConfirm({title:'删除这个清单？',description:'只删除清单副本，不影响私人到访记录。已经发送的文件不会被撤回。',action:async()=>{await api('deleteList',{id:activeList.id});setActiveListId(null);await reload()}})}><Trash2 size={18}/></button></div></div>{!activeList.items.length&&<Empty><EmptyTitle>清单里还没有记录</EmptyTitle><EmptyDescription>在「回顾」打开到访记录，点击「加入清单」。</EmptyDescription><button className="secondary" onClick={()=>setTab('journal')}>挑选到访记录</button></Empty>}<div className="record-grid">{activeList.items.map(item=><article className="visit-card snapshot" key={item.id}><div className="card-top"><span className="category">{item.date}</span><Rating value={item.rating}/></div><h3>{item.name}</h3><p className="address">{item.address}</p>{item.photoIds[0]&&<img className="visit-cover" src={`/api/photos/${item.photoIds[0]}`} alt="清单照片"/>}<p className="card-note">{item.note}</p><button className="text-button danger" onClick={()=>setConfirm({title:'从清单移除？',description:'私人到访记录会保留。',action:async()=>{await api('removeItem',{id:item.id});await reload()}})}>移除副本</button></article>)}</div></div>:lists.length?<div className="record-grid">{lists.map(l=><button className="list-card" key={l.id} onClick={()=>setActiveListId(l.id)}><Heart size={25}/><h3>{l.title}</h3><span>{l.items.length} 条精选记录</span><ChevronRight size={20}/></button>)}</div>:<Empty className="empty-card compact"><Heart size={35}/><EmptyTitle>收藏喜欢的好去处</EmptyTitle><EmptyDescription>例如「周末咖啡地图」或「想带朋友去的店」。</EmptyDescription><button className="primary" onClick={()=>email?setListDialog(true):start()}><Plus size={18}/>创建第一份清单</button></Empty>}</TabsContent>
 <TabsContent value="settings"><div className="settings-grid"><section className="settings-card"><h2>记录方式</h2><div className="setting-row"><span>主动打卡</span><span className="badge"><Check size={14}/>已启用</span></div><p>打开「记一笔」，定位并选择店铺，或手动填写。锁屏、离开网页后不会持续跟踪位置。</p><p>定位只在你点击时获取。拒绝定位也可以记录；评分允许半星，未评分不计入均值。</p></section><section className="settings-card"><h2>保存与账号</h2><div className="setting-row"><span>{email||'尚未登录'}</span>{email&&<a href="/signout-with-chatgpt?return_to=%2F" target="_top">退出</a>}</div><p>记录和照片保存在网站云端，同一账号跨设备访问。此网页版不使用 iCloud，保存需要联网。</p><button className="secondary" onClick={reload} disabled={!email||loading}><RefreshCw size={16}/>刷新记录</button></section><section className="settings-card"><h2>放到 iPhone 主屏幕</h2><ol><li>用 Safari 打开本站。</li><li>点分享按钮，选择「添加到主屏幕」。</li><li>名称保留「行迹」，点「添加」。</li></ol><p>之后从桌面图标打开即可。首次使用需登录同一个 ChatGPT 账号。</p></section><section className="settings-card"><h2>数据与分享</h2><p>导出包含全部记录与照片。清单仅分享主动选入的副本，照片已移除定位元数据。已发送的文件无法撤回。</p><button className="secondary" disabled={!email||exporting} onClick={exportAll}><Download size={16}/>{exporting?'正在准备文件':'导出全部数据'}</button><p className="hint">导出为 JSON 文件，暂不支持备份导入。</p></section><section className="settings-card danger-card"><h2>删除全部数据</h2><p>包括到访、照片和清单，删除后不可恢复。</p><input aria-label="确认删除文字" placeholder="输入：删除我的全部记录" value={deleteText} onChange={e=>setDeleteText(e.target.value)}/><button className="secondary danger" disabled={!email||deleteText!=='删除我的全部记录'} onClick={()=>setConfirm({title:'永久删除全部数据？',description:'请确认已经导出需要保留的记录。此操作无法撤销。',action:async()=>{await api('deleteAll',{confirm:deleteText});setDeleteText('');setSelected(null);await reload()}})}><Trash2 size={16}/>删除全部数据</button></section></div></TabsContent>
 </Tabs><footer>行迹 · 留下生活里的好去处</footer>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!saving){if(pending.length||draft?.name.trim()){setConfirm({title:'放弃当前编辑？',description:'尚未保存的文字和新增照片将丢弃，已经保存的内容会保留。',action:async()=>clearDraft()})}else clearDraft()}}}><DialogContent className="entry-dialog" showCloseButton={!saving}><DialogTitle>{draft&&visits.some(v=>v.id===draft.id)?'编辑到访':'记下这次到访'}</DialogTitle><DialogDescription>到访时间自动填写；照片与感受可稍后补充。</DialogDescription>{draft&&<form onSubmit={save} className="entry-form"><fieldset disabled={saving}><div className="entry-location"><button type="button" className="secondary" onClick={locate} disabled={locating}>{locating?<LoaderCircle className="spin" size={18}/>:<Navigation size={18}/>}获取当前位置</button><button type="button" className="text-button" onClick={()=>setShowSearch(!showSearch)}>搜索店铺</button></div>{draft.location&&<p className="location-state"><Check size={14}/>已记录位置{draft.location.accuracy!==null?` · 精度约 ${Math.round(draft.location.accuracy)} 米`:''}<button type="button" onClick={()=>setDraft({...draft,location:null})}>移除</button></p>}{showSearch&&<Nearby position={draft.location} onSelect={p=>setDraft({...draft,placeKey:`amap:${p.id}`,name:p.name,address:typeof p.address==='string'?p.address:'',location:{lat:p.location.getLat(),lng:p.location.getLng(),system:'GCJ02',source:'amap',accuracy:null}})}/>}
 <label>店铺名称 <span>*</span><input required maxLength={100} value={draft.name} placeholder="例如：街角咖啡（中心店）" onChange={e=>setDraft({...draft,name:e.target.value,placeKey:draft.name===e.target.value?draft.placeKey:draft.id})}/></label>
 {!visits.some(v=>v.id===draft.id)&&visits.length>0&&<details><summary>再次到访已有店铺</summary><div className="existing-places">{[...new Map(visits.map(v=>[v.placeKey,v])).values()].map(v=><button type="button" className="secondary" key={v.placeKey} onClick={()=>setDraft({...draft,name:v.name,address:v.address,category:v.category,placeKey:v.placeKey,location:v.location})}>{v.name}</button>)}</div></details>}
 <label>地址<input maxLength={250} value={draft.address} placeholder="填写分店地址，方便区分同名门店" onChange={e=>setDraft({...draft,address:e.target.value})}/></label><div className="form-columns"><label>类型<Choice label="店铺类型" value={draft.category} onChange={v=>setDraft({...draft,category:v as Visit['category']})} options={['餐厅','咖啡','购物','其他'].map(v=>[v,v])}/></label><label>评分<Choice label="到访评分" value={draft.rating?.toString()||'none'} onChange={v=>setDraft({...draft,rating:v==='none'?null:Number(v)})} options={[["none","暂不评分"],...Array.from({length:10},(_,i)=>[String((i+1)/2),`${((i+1)/2).toFixed(1)} 分`] as [string,string])]}/></label></div>
 <label>到达时间<input required type="datetime-local" value={localInput(draft.arrived)} onChange={e=>{if(e.target.value)setDraft({...draft,arrived:new Date(e.target.value).toISOString()})}}/></label><label>离开时间（可选）<input type="datetime-local" value={draft.departed?localInput(draft.departed):''} onChange={e=>setDraft({...draft,departed:e.target.value?new Date(e.target.value).toISOString():null})}/></label><p className="hint">输入时间使用当前设备时区；日期筛选和共享日期使用北京时间。</p><label>这次的感受<textarea rows={3} maxLength={5000} value={draft.note} placeholder="喜欢的菜、座位、服务，或任何想记住的小事……" onChange={e=>setDraft({...draft,note:e.target.value})}/></label>
 <div className="photo-label"><span>照片 <small>{draft.photoIds.length+pending.length}/6</small></span><label className="text-button"><Camera size={18}/>添加照片<input hidden type="file" accept="image/*" multiple onChange={e=>{const files=Array.from(e.target.files??[]);const room=6-draft.photoIds.length-pending.length;if(files.length>room)toast('每次到访最多 6 张照片');setPending(p=>[...p,...files.slice(0,room).map(file=>({id:crypto.randomUUID(),file,preview:URL.createObjectURL(file)}))]);e.target.value=''}}/></label></div>
 <div className="photo-grid">{draft.photoIds.map(id=><div key={id}><img src={`/api/photos/${id}`} alt="已保存照片"/><button type="button" aria-label="删除照片" onClick={()=>setConfirm({title:'删除这张照片？',description:'保存于私人记录的照片将被删除，已有清单副本不受影响。',action:()=>removePhoto(id)})}><X size={15}/></button></div>)}{pending.map(p=><div key={p.id}><img src={p.preview} alt="待上传照片"/><button type="button" aria-label="取消上传照片" onClick={()=>{URL.revokeObjectURL(p.preview);setPending(ps=>ps.filter(x=>x.id!==p.id))}}><X size={15}/></button><span>待上传</span></div>)}</div><p className="hint">上传时压缩照片并移除定位元数据。</p></fieldset>{formError&&<p role="alert" className="form-error">{formError}</p>}<button className="primary save-button" type="submit" disabled={saving||!online}>{saving?<><LoaderCircle className="spin" size={18}/>正在保存…</>:<><Check size={18}/>保存这次到访</>}</button></form>}</DialogContent></Dialog>
 <Sheet open={!!detail} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="detail-sheet">{detail&&<><SheetTitle>{detail.name}</SheetTitle><SheetDescription>{detail.address||'未填写地址'}</SheetDescription><div className="detail-body"><div className="card-top"><span className="category">{detail.category}</span><Rating value={detail.rating}/></div><p><b>到达</b>　{new Date(detail.arrived).toLocaleString('zh-CN')}</p>{detail.departed&&<p><b>离开</b>　{new Date(detail.departed).toLocaleString('zh-CN')}</p>}<p className="detail-note">{detail.note||'还没有写下感受，编辑记录来补充吧。'}</p><div className="detail-photos">{detail.photoIds.map(id=><a key={id} href={`/api/photos/${id}`} target="_blank" rel="noreferrer"><img src={`/api/photos/${id}`} alt={`${detail.name}的探店照片`}/></a>)}</div><div className="actions"><button className="primary" onClick={()=>start(detail)}>编辑记录</button><button className="secondary" onClick={()=>{setTargetList(lists[0]?.id||'');setShareVisit(detail)}}><Heart size={17}/>加入清单</button><button className="icon-button danger" aria-label="删除到访" onClick={()=>setConfirm({title:'删除这次到访？',description:'这次到访与照片会删除，已加入清单的独立副本会保留。',action:async()=>{await api('deleteVisit',{id:detail.id});setSelected(null);await reload()}})}><Trash2 size={18}/></button></div><a className="text-button map-link" href={`https://uri.amap.com/search?keyword=${encodeURIComponent(detail.name+' '+detail.address)}&src=xingji&callnative=1`} target="_blank" rel="noreferrer"><ExternalLink size={16}/>在高德查看</a><hr/><h3>这家分店的到访</h3><p className="hint">{visits.filter(v=>v.placeKey===detail.placeKey).length} 次到访 · 历史均分 {average(visits.filter(v=>v.placeKey===detail.placeKey))?.toFixed(1)??'未评分'}</p>{visits.filter(v=>v.placeKey===detail.placeKey).map(v=><button className="history-row" key={v.id} onClick={()=>setSelected(v)}><span>{fmt(v.arrived)}</span><Rating value={v.rating}/></button>)}<button className="secondary" onClick={()=>{const v={...blank(),name:detail.name,address:detail.address,category:detail.category,placeKey:detail.placeKey,location:detail.location};start(v)}}><Plus size={16}/>再次到访</button></div></>}</SheetContent></Sheet>
 <Dialog open={listDialog} onOpenChange={setListDialog}><DialogContent><DialogTitle>新建探店清单</DialogTitle><DialogDescription>挑一个名字，把喜欢的店收在一起。</DialogDescription><input aria-label="清单名称" maxLength={60} value={listTitle} onChange={e=>setListTitle(e.target.value)} placeholder="例如：值得再去的咖啡店"/><button className="primary" onClick={createList} disabled={busy||!listTitle.trim()}>创建清单</button></DialogContent></Dialog>
 <Dialog open={!!shareVisit} onOpenChange={o=>!o&&setShareVisit(null)}><DialogContent><DialogTitle>预览清单内容</DialogTitle><DialogDescription>只复制下方内容，不包含定位坐标、精确时间或其他到访历史。</DialogDescription>{shareVisit&&<><article className="share-preview"><span className="category">{chinaDate(shareVisit.arrived)}</span><h3>{shareVisit.name}</h3><p>{shareVisit.address}</p><Rating value={shareVisit.rating}/><p className="detail-note">{shareVisit.note}</p><div className="photo-grid">{shareVisit.photoIds.map(id=><img key={id} src={`/api/photos/${id}`} alt="即将加入清单的照片"/>)}</div></article>{lists.length?<><Choice label="目标清单" value={targetList} onChange={setTargetList} options={lists.map(l=>[l.id,l.title])}/><button className="primary" onClick={addSnapshot} disabled={busy||!targetList}>{busy?'正在加入':'确认加入清单'}</button></>:<button className="primary" onClick={()=>setListDialog(true)}>先创建一个清单</button>}</>}</DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={o=>!o&&!busy&&setConfirm(null)}><AlertDialogContent><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.description}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(!confirm)return;setBusy(true);try{await confirm.action();setConfirm(null)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}>{busy?'处理中':'确认'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
