'use client';
import {useEffect,useRef,useState} from 'react';
import type {Visit} from '@/lib/diary';
import {MapPin,ExternalLink,Search,LoaderCircle} from 'lucide-react';
import {Empty,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
type POI={id:string;name:string;address:string;location:{getLat():number;getLng():number}};
declare global{interface Window{AMap:any;_AMapSecurityConfig:any}}
let loader:Promise<any>|undefined;
export async function loadMap(){if(!loader)loader=(async()=>{const response=await fetch('/api/map-config');const config=await response.json() as {enabled:boolean;key:string};if(!config.enabled)throw new Error('尚未开通地图服务');window._AMapSecurityConfig={serviceHost:location.origin+'/api/amap'};return await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=`https://webapi.amap.com/maps?v=2.0&key=${encodeURIComponent(config.key)}&plugin=AMap.PlaceSearch`;script.onload=()=>window.AMap?resolve(window.AMap):reject(new Error('地图加载失败'));script.onerror=()=>reject(new Error('地图加载失败，请检查网络'));document.head.appendChild(script)})})().catch(e=>{loader=undefined;throw e});return loader}
export async function convert(A:any,loc:NonNullable<Visit['location']>):Promise<[number,number]>{if(loc.system==='GCJ02')return [loc.lng,loc.lat];return new Promise((resolve,reject)=>A.convertFrom([loc.lng,loc.lat],'gps',(status:string,r:any)=>status==='complete'?resolve([r.locations[0].getLng(),r.locations[0].getLat()]):reject(new Error('坐标转换失败'))))}
export function Nearby({position,onSelect}:{position:Visit['location'];onSelect:(poi:POI)=>void}){const [q,setQ]=useState('');const [results,setResults]=useState<POI[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function search(){setBusy(true);setMessage('');try{const A=await loadMap();const service=new A.PlaceSearch({pageSize:10,extensions:'base'});const result:any=await new Promise(async(resolve,reject)=>{const done=(status:string,r:any)=>status==='complete'?resolve(r):status==='no_data'?resolve({poiList:{pois:[]}}):reject(new Error('店铺搜索失败，请稍后重试'));if(position){try{const center=await convert(A,position);service.searchNearBy(q.trim()||'美食|咖啡|购物',center,1000,done)}catch(e){reject(e)}}else service.search(q.trim(),done)});setResults(result.poiList.pois);if(!result.poiList.pois.length)setMessage('没有找到匹配店铺，可换个关键词或手动填写')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}return <div className="nearby"><div className="search-row"><input aria-label="搜索店铺" value={q} onChange={e=>setQ(e.target.value)} placeholder="店名、商圈或城市"/><button type="button" className="secondary" onClick={search} disabled={busy||(!position&&!q.trim())}>{busy?<LoaderCircle className="spin" size={17}/>:<Search size={17}/>}搜索</button></div>{message&&<p className="hint">{message}。可 <a href={`https://uri.amap.com/search?keyword=${encodeURIComponent(q||'附近美食')}&src=xingji&callnative=1`} target="_blank" rel="noreferrer">在高德查看</a>，返回后填写店名。</p>}<div className="poi-results">{results.map(p=><button type="button" key={p.id} onClick={()=>{onSelect(p);setResults([])}}><b>{p.name}</b><small>{typeof p.address==='string'?p.address:''}</small></button>)}</div></div>}
export default function MapView({visits,onSelect}:{visits:Visit[];onSelect:(v:Visit)=>void}){const ref=useRef<HTMLDivElement>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(true);useEffect(()=>{let stopped=false;let map:any;(async()=>{try{const A=await loadMap();if(stopped)return;map=new A.Map(ref.current,{zoom:12,viewMode:'2D'});const seen=new Set<string>();let count=0;let gaps=0;for(const v of visits){if(stopped)return;if(!v.location||seen.has(v.placeKey))continue;seen.add(v.placeKey);try{const position=await convert(A,v.location);if(stopped)return;const marker=new A.Marker({position,title:v.name});marker.on('click',()=>onSelect(v));map.add(marker);count++}catch{gaps++}}if(count)map.setFitView();if(gaps)setError(`${gaps} 个位置转换失败，未绘制在地图上`)}catch(e){if(!stopped)setError((e as Error).message)}finally{if(!stopped)setBusy(false)}})();return()=>{stopped=true;map?.destroy()}},[visits]);return <section className="map-wrap"><div className="map-canvas" ref={ref}/>{busy&&<div className="map-message"><LoaderCircle className="spin"/>正在加载地图</div>}{error&&<Empty className="map-message"><MapPin size={32}/><EmptyTitle>{error}</EmptyTitle><EmptyDescription>到访记录仍可正常保存。开通高德服务后，可在这里查看店铺标记。</EmptyDescription><a className="secondary" href="https://uri.amap.com/search?keyword=美食&src=xingji&callnative=1" target="_blank" rel="noreferrer"><ExternalLink size={16}/>打开高德地图</a></Empty>}<div className="map-caption">只显示有位置的到访 · 点击标记查看记录</div></section>}
